using System.Globalization;

namespace HDRScreenMirror;

internal enum UiLanguage
{
    Chinese,
    English
}

internal static class Localization
{
    internal const string Automatic = "auto";
    internal const string SimplifiedChinese = "zh-CN";
    internal const string English = "en-US";

    private static readonly IReadOnlyDictionary<string, string> ChineseStrings =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["CaptureDisplay"] = "捕获显示器",
            ["OutputDisplay"] = "输出显示器",
            ["PaperWhite"] = "SDR 白点亮度",
            ["Present"] = "呈现",
            ["LuminanceAnalysis"] = "亮度分析",
            ["ColorAnalysis"] = "色域分析",
            ["InteractionSafety"] = "交互与安全",
            ["WindowManagement"] = "窗口管理",
            ["ScreenshotSettings"] = "截图设置",
            ["GlobalHotkeys"] = "全局快捷键",
            ["CurrentStatus"] = "当前状态",
            ["ResetDefault"] = "恢复默认",
            ["AllOutputs"] = "输出到所有同显卡显示器",
            ["FrameRateMode"] = "帧率策略",
            ["FrameRateFollowOutput"] = "跟随输出显示器",
            ["FrameRateFixed"] = "固定上限",
            ["FrameRateUnlimited"] = "不限制",
            ["FrameRateUnit"] = "fps",
            ["StatusOverlay"] = "状态面板",
            ["RenderCursor"] = "在输出屏渲染鼠标",
            ["ShowPointerLuminance"] = "显示鼠标指针区域亮度",
            ["FalseColor"] = "输出亮度伪色图",
            ["LuminanceMarkers"] = "标记画面最高与最低亮度",
            ["ShowAblEstimate"] = "显示 ABL 后估算亮度",
            ["AblProfile"] = "ABL 配置档案",
            ["ManageAblProfiles"] = "管理配置…",
            ["CieAnalysis"] = "实时色域分析面板",
            ["MouseThrough"] = "鼠标穿透输出画面",
            ["EnableHotkeys"] = "启用全局快捷键",
            ["MinimizeToTray"] = "关闭时最小化到托盘",
            ["MoveOutputWindows"] = "开始镜像时将输出屏窗口移到捕获屏",
            ["ScreenshotAutomatic"] = "自动保存",
            ["ScreenshotPrompt"] = "每次手动选择位置",
            ["ChooseFolder"] = "选择目录",
            ["RefreshDisplays"] = "重新扫描显示器",
            ["StartMirror"] = "开始 HDR 镜像",
            ["StartAnalysis"] = "开始 HDR 分析",
            ["Stop"] = "停止",
            ["About"] = "关于",
            ["OperationMode"] = "模式",
            ["OperationModeMirror"] = "HDR 多屏镜像",
            ["OperationModeAnalysis"] = "HDR 单屏分析",
            ["Language"] = "语言",
            ["ShortcutText"] = "Ctrl + F8    开始或停止镜像\r\n" +
                               "Ctrl + F9    开启或关闭亮度伪色图\r\n" +
                               "Ctrl + F10   截取输出画面\r\n" +
                               "Ctrl + F11   显示或隐藏状态面板\r\n" +
                               "Ctrl + F12   召回主界面到捕获显示器",
            ["PaperWhiteHelp"] = "nits。仅影响 SDR 回退、SDR 亮度分析与鼠标亮度；HDR 主画面不受影响。",
            ["StatusEnumerating"] = "正在枚举显示器……",
            ["StatusNoDisplays"] = "没有找到连接到桌面的 DXGI 显示器。",
            ["StatusFoundDisplays"] = "找到 {0} 个显示输出。请选择捕获与输出显示器。",
            ["StatusFoundSingleDisplay"] = "找到 1 个显示输出。可选择 HDR 单屏分析；HDR 多屏镜像需要连接输出显示器。",
            ["EnumerateFailed"] = "枚举显示器失败",
            ["NoGpuOutputs"] = "没有找到与捕获屏连接在同一块 GPU 上的其他显示器。",
            ["NoOutput"] = "没有可用输出",
            ["NonHdrWarning"] = "以下目标没有报告 HDR10 色彩空间：{0}\r\n继续运行可能导致亮度或颜色不正确。仍然继续吗？",
            ["NonHdrTitle"] = "部分目标显示器未开启 HDR",
            ["StatusMirroring"] = "镜像运行中，正在输出到 {0} 个显示器。",
            ["StatusAnalyzing"] = "单屏分析运行中，状态面板显示在捕获显示器上。",
            ["StartFailed"] = "启动 HDR 镜像失败",
            ["StartAnalysisFailed"] = "启动 HDR 分析失败",
            ["SameDisplay"] = "捕获显示器和输出显示器不能相同。",
            ["CrossGpu"] = "当前版本不支持跨 GPU 镜像。请选择连接在同一块显卡上的输出。",
            ["StatusStopped"] = "已停止。",
            ["RuntimeFailed"] = "HDR 镜像运行失败",
            ["RuntimeAnalysisFailed"] = "HDR 分析运行失败",
            ["FalseColorNeedsOutput"] = "单屏分析模式不支持亮度伪色输出。",
            ["NoVisibleAnalysisTitle"] = "没有可见分析内容",
            ["NoVisibleAnalysisContent"] = "请至少启用状态面板、最高与最低亮度标记或实时色域分析面板中的一项。",
            ["CaptureExclusionFailed"] = "Windows 无法将分析界面从屏幕捕获中排除。为避免状态面板污染亮度统计，单屏分析未启动。",
            ["HotkeyFailed"] = "以下全局快捷键注册失败，可能已被其他程序占用：{0}",
            ["ScreenshotNeedsMirror"] = "请先开始镜像，再截取输出画面。",
            ["ScreenshotSaved"] = "截图已保存：{0}",
            ["ScreenshotsSaved"] = "已保存 {0} 张截图：{1}",
            ["ScreenshotSuccessToast"] = "截图已保存",
            ["ScreenshotFailed"] = "保存截图失败",
            ["TrayShow"] = "显示主界面",
            ["TrayStart"] = "开始镜像",
            ["TrayStop"] = "停止镜像",
            ["TrayStartAnalysis"] = "开始单屏分析",
            ["TrayStopAnalysis"] = "停止单屏分析",
            ["TrayExit"] = "退出程序",
            ["TrayRunning"] = "HDRScreenMirror 正在镜像",
            ["TrayAnalyzing"] = "HDRScreenMirror 正在分析",
            ["AboutTitle"] = "关于 HDRScreenMirror",
            ["AboutSubtitle"] = "Windows HDR 屏幕镜像工具",
            ["AboutVersion"] = "版本 {0}  ·  x64",
            ["AboutDetails"] = "捕获：DXGI Desktop Duplication\r\n渲染：Direct3D 11\r\n输出：FP16 scRGB HDR",
            ["Close"] = "关闭",
            ["HdrOn"] = "HDR 已开启",
            ["HdrOff"] = "HDR 未开启",
            ["OverlayStarting"] = "正在启动",
            ["OverlayWaiting"] = "等待输入信号",
            ["OverlayHotkeys"] = "Ctrl + F8 停止   ·   F9 伪色   ·   F10 截图   ·   F11 面板   ·   F12 召回",
            ["OverlayHotkeysAnalysis"] = "Ctrl + F8 停止   ·   F11 面板   ·   F12 召回",
            ["SingleDisplayRoute"] = "{0}  ·  单屏分析",
            ["OverlayMetrics"] = "{0,4:F1} fps   鼠标 {1}",
            ["OverlayFrameLuminance"] = "画面  平均 {0:F1}  最大 {1:F1}  最小 {2:F1} nits",
            ["OverlayPointerLuminance"] = "鼠标指针区域亮度   {0:F3} nits",
            ["OverlayPointerOutside"] = "鼠标指针区域亮度   不在捕获区域",
            ["OverlayFalseColor"] = "亮度伪色色阶",
            ["OverlayFrameTitle"] = "画面亮度",
            ["OverlayAverage"] = "平均",
            ["OverlayMaximum"] = "最大",
            ["OverlayMinimum"] = "最小",
            ["OverlayPointerTitle"] = "鼠标指针区域亮度",
            ["OverlayPointerOutsideShort"] = "不在捕获区域",
            ["OverlayPointerOriginal"] = "原始  {0:F3} nits",
            ["OverlayPointerScaled"] = "ABL 后  {0:F3} nits",
            ["OverlayAblTitle"] = "ABL 后估算亮度",
            ["OverlayAblSummary"] = "等效 APL {0:F1}%   ·   整体缩放 {1:F1}%   ·   亮度下降 {2:F1}%",
            ["CieFrameUsage"] = "当前画面色域使用热力图",
            ["CieOutside"] = "范围外",
            ["CieWaiting"] = "等待色域数据",
            ["CieAnalyzedPixels"] = "分析像素 {0:N0}  ·  低于 0.01 nits 不计入",
            ["MarkerMaximum"] = "最高",
            ["MarkerMinimum"] = "最低",
            ["CursorOn"] = "鼠标显示",
            ["CursorOff"] = "鼠标隐藏",
            ["NeedOutput"] = "至少需要一个输出显示器。",
            ["SessionStarted"] = "镜像会话已经启动。",
            ["OpenAdapterFailed"] = "无法重新打开捕获显示器对应的显卡。",
            ["OpenCaptureFailed"] = "无法重新打开捕获显示器。",
            ["D3DReady"] = "Direct3D 11 已初始化，正在等待第一帧……",
            ["AnalysisD3DReady"] = "Direct3D 11 分析管线已初始化，正在等待第一帧……",
            ["SecureDesktopWaiting"] = "检测到 Windows 安全桌面，镜像已暂停；关闭管理员提示后将自动恢复。",
            ["AnalysisSecureDesktopWaiting"] = "检测到 Windows 安全桌面，分析已暂停；关闭管理员提示后将自动恢复。",
            ["SecureDesktopPaused"] = "安全桌面，镜像已暂停",
            ["CaptureResumed"] = "安全桌面已关闭，正在恢复镜像……",
            ["AnalysisCaptureResumed"] = "安全桌面已关闭，正在恢复分析……",
            ["OutputCrossGpu"] = "输出显示器 {0} 不在捕获显卡上，当前版本不支持跨 GPU 输出。",
            ["OpenOutputFailed"] = "无法打开输出显示器 {0}。",
            ["Fp16Unsupported"] = "目标显示器 {0} 不支持 FP16 scRGB 交换链。请确认 Windows HDR 已开启。",
            ["FrameLatencyUnavailable"] = "无法为输出显示器 {0} 创建帧延迟等待对象。",
            ["FrameLatencyWaitFailed"] = "等待输出显示器接受下一帧时失败。",
            ["FrameRateWaitFailed"] = "等待下一个固定帧率时间点时失败。",
            ["Hdr"] = "HDR",
            ["SdrFallback"] = "SDR 回退",
            ["CursorDisabled"] = "已关闭",
            ["CursorHidden"] = "隐藏",
            ["CursorRendered"] = "已渲染",
            ["CursorWaiting"] = "等待形状",
            ["RunningStatus"] = "运行中  {0:F1} fps  输入={1}  {2}  尺寸={3}×{4}  鼠标={5}  总帧={6}",
            ["Running"] = "运行中",
            ["UnsupportedFormat"] = "不支持捕获格式 {0}。",
            ["InvalidPointerBuffer"] = "Desktop Duplication 返回了无效的鼠标形状缓冲区大小。",
            ["AppStartFailed"] = "HDRScreenMirror 启动失败",
            ["AblProfilesTitle"] = "ABL 亮度配置",
            ["AblProfiles"] = "配置档案",
            ["AblMeasurements"] = "窗口峰值亮度",
            ["AblProfileName"] = "配置名称",
            ["AblEotfTitle"] = "峰值亮度 EOTF",
            ["AblEotfReset"] = "恢复标准 PQ",
            ["AblEotfNoPeak"] = "请先填写 1% APL 峰值亮度",
            ["AblEotfClipValue"] = "裁切点  PQ {0:F1}%  ·  {1} nits",
            ["AblAplColumn"] = "APL",
            ["AblPeakColumn"] = "峰值亮度（nits）",
            ["AblRequiredApl"] = "{0}%  必填",
            ["AblNew"] = "新建",
            ["AblDuplicate"] = "复制",
            ["AblDelete"] = "删除",
            ["AblSave"] = "保存",
            ["AblCancel"] = "取消",
            ["AblDefaultProfileName"] = "配置 {0}",
            ["AblCopyName"] = "{0} 副本",
            ["AblDeleteConfirm"] = "确定删除配置“{0}”吗？",
            ["AblDeleteTitle"] = "删除 ABL 配置",
            ["AblInvalidPeak"] = "亮度必须是大于 0 且不超过 10000 的数字。",
            ["AblInvalidProfileTitle"] = "ABL 配置不完整",
            ["AblInvalidProfile"] = "配置“{0}”必须填写名称、1% 峰值亮度和 100% 峰值亮度。",
            ["AblUnnamedProfile"] = "未命名配置",
            ["AblEmptyTitle"] = "还没有 ABL 配置",
            ["AblEmptyHelp"] = "点击左侧蓝色“新建”按钮，填写 1% 与 100% APL 峰值亮度。"
        };

    private static readonly IReadOnlyDictionary<string, string> EnglishStrings =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["CaptureDisplay"] = "Capture display",
            ["OutputDisplay"] = "Output display",
            ["PaperWhite"] = "SDR white level",
            ["Present"] = "Presentation",
            ["LuminanceAnalysis"] = "Luminance analysis",
            ["ColorAnalysis"] = "Gamut analysis",
            ["InteractionSafety"] = "Interaction & safety",
            ["WindowManagement"] = "Window management",
            ["ScreenshotSettings"] = "Screenshots",
            ["GlobalHotkeys"] = "Global hotkeys",
            ["CurrentStatus"] = "Current status",
            ["ResetDefault"] = "Reset default",
            ["AllOutputs"] = "All displays on this GPU",
            ["FrameRateMode"] = "Frame rate",
            ["FrameRateFollowOutput"] = "Follow output display",
            ["FrameRateFixed"] = "Fixed limit",
            ["FrameRateUnlimited"] = "Unlimited",
            ["FrameRateUnit"] = "fps",
            ["StatusOverlay"] = "Status panel",
            ["RenderCursor"] = "Render cursor on output",
            ["ShowPointerLuminance"] = "Show cursor area luminance",
            ["FalseColor"] = "Output luminance false color",
            ["LuminanceMarkers"] = "Mark highest and lowest luminance",
            ["ShowAblEstimate"] = "Show ABL estimated luminance",
            ["AblProfile"] = "ABL profile",
            ["ManageAblProfiles"] = "Manage profiles…",
            ["CieAnalysis"] = "Real-time gamut analysis panel",
            ["MouseThrough"] = "Click through mirror",
            ["EnableHotkeys"] = "Enable global hotkeys",
            ["MinimizeToTray"] = "Minimize to tray on close",
            ["MoveOutputWindows"] = "Move output windows to capture display on start",
            ["ScreenshotAutomatic"] = "Save automatically",
            ["ScreenshotPrompt"] = "Choose a location each time",
            ["ChooseFolder"] = "Choose folder",
            ["RefreshDisplays"] = "Rescan displays",
            ["StartMirror"] = "Start HDR mirror",
            ["StartAnalysis"] = "Start HDR analysis",
            ["Stop"] = "Stop",
            ["About"] = "About",
            ["OperationMode"] = "Mode",
            ["OperationModeMirror"] = "HDR multi-display mirroring",
            ["OperationModeAnalysis"] = "HDR single-display analysis",
            ["Language"] = "Language",
            ["ShortcutText"] = "Ctrl + F8    Start or stop mirroring\r\n" +
                               "Ctrl + F9    Toggle luminance false color\r\n" +
                               "Ctrl + F10   Capture output image\r\n" +
                               "Ctrl + F11   Show or hide the status panel\r\n" +
                               "Ctrl + F12   Recall this window to the capture display",
            ["PaperWhiteHelp"] = "nits. Affects SDR fallback, SDR luminance analysis, and cursor brightness; the HDR image is unchanged.",
            ["StatusEnumerating"] = "Enumerating displays…",
            ["StatusNoDisplays"] = "No desktop attached DXGI display was found.",
            ["StatusFoundDisplays"] = "Found {0} display outputs. Select a capture and output display.",
            ["StatusFoundSingleDisplay"] = "Found 1 display output. Select HDR single-display analysis, or connect an output display for HDR multi-display mirroring.",
            ["EnumerateFailed"] = "Display enumeration failed",
            ["NoGpuOutputs"] = "No other display was found on the same GPU as the capture display.",
            ["NoOutput"] = "No output available",
            ["NonHdrWarning"] = "These targets do not report an HDR10 color space: {0}\r\nContinuing may produce incorrect brightness or color. Continue anyway?",
            ["NonHdrTitle"] = "HDR is not enabled on some targets",
            ["StatusMirroring"] = "Mirroring to {0} display outputs.",
            ["StatusAnalyzing"] = "Single display analysis is running with the status panel on the capture display.",
            ["StartFailed"] = "Failed to start HDR mirroring",
            ["StartAnalysisFailed"] = "Failed to start HDR analysis",
            ["SameDisplay"] = "The capture and output displays cannot be the same.",
            ["CrossGpu"] = "Cross GPU mirroring is not supported. Select an output connected to the same GPU.",
            ["StatusStopped"] = "Stopped.",
            ["RuntimeFailed"] = "HDR mirroring failed",
            ["RuntimeAnalysisFailed"] = "HDR analysis failed",
            ["FalseColorNeedsOutput"] = "Luminance false color output is unavailable in single display analysis mode.",
            ["NoVisibleAnalysisTitle"] = "No visible analysis content",
            ["NoVisibleAnalysisContent"] = "Enable at least one of the status panel, highest and lowest luminance markers, or the real-time gamut analysis panel.",
            ["CaptureExclusionFailed"] = "Windows could not exclude the analysis interface from screen capture. Single display analysis was not started because the interface would contaminate luminance measurements.",
            ["HotkeyFailed"] = "These global hotkeys could not be registered and may already be in use: {0}",
            ["ScreenshotNeedsMirror"] = "Start mirroring before capturing the output image.",
            ["ScreenshotSaved"] = "Screenshot saved: {0}",
            ["ScreenshotsSaved"] = "Saved {0} screenshots to {1}",
            ["ScreenshotSuccessToast"] = "Screenshot saved",
            ["ScreenshotFailed"] = "Failed to save screenshot",
            ["TrayShow"] = "Show control panel",
            ["TrayStart"] = "Start mirroring",
            ["TrayStop"] = "Stop mirroring",
            ["TrayStartAnalysis"] = "Start single display analysis",
            ["TrayStopAnalysis"] = "Stop single display analysis",
            ["TrayExit"] = "Exit",
            ["TrayRunning"] = "HDRScreenMirror is mirroring",
            ["TrayAnalyzing"] = "HDRScreenMirror is analyzing",
            ["AboutTitle"] = "About HDRScreenMirror",
            ["AboutSubtitle"] = "Windows HDR screen mirroring tool",
            ["AboutVersion"] = "Version {0}  ·  x64",
            ["AboutDetails"] = "Capture: DXGI Desktop Duplication\r\nRendering: Direct3D 11\r\nOutput: FP16 scRGB HDR",
            ["Close"] = "Close",
            ["HdrOn"] = "HDR enabled",
            ["HdrOff"] = "HDR disabled",
            ["OverlayStarting"] = "Starting",
            ["OverlayWaiting"] = "Waiting for input",
            ["OverlayHotkeys"] = "Ctrl + F8 Stop   ·   F9 False color   ·   F10 Capture   ·   F11 Panel   ·   F12 Recall",
            ["OverlayHotkeysAnalysis"] = "Ctrl + F8 Stop   ·   F11 Panel   ·   F12 Recall",
            ["SingleDisplayRoute"] = "{0}  ·  SINGLE DISPLAY ANALYSIS",
            ["OverlayMetrics"] = "{0,4:F1} fps   CURSOR {1}",
            ["OverlayFrameLuminance"] = "AVG {0:F1}  MAX {1:F1}  MIN {2:F1} nits",
            ["OverlayPointerLuminance"] = "CURSOR AREA   {0:F3} nits",
            ["OverlayPointerOutside"] = "CURSOR AREA   Outside capture area",
            ["OverlayFalseColor"] = "FALSE COLOR SCALE",
            ["OverlayFrameTitle"] = "Frame luminance",
            ["OverlayAverage"] = "Average",
            ["OverlayMaximum"] = "Maximum",
            ["OverlayMinimum"] = "Minimum",
            ["OverlayPointerTitle"] = "Cursor area luminance",
            ["OverlayPointerOutsideShort"] = "Outside capture area",
            ["OverlayPointerOriginal"] = "Original  {0:F3} nits",
            ["OverlayPointerScaled"] = "After ABL  {0:F3} nits",
            ["OverlayAblTitle"] = "ABL estimated luminance",
            ["OverlayAblSummary"] = "Equivalent APL {0:F1}%   ·   Scale {1:F1}%   ·   Reduction {2:F1}%",
            ["CieFrameUsage"] = "CURRENT FRAME GAMUT USAGE HEATMAP",
            ["CieOutside"] = "Outside",
            ["CieWaiting"] = "Waiting for gamut data",
            ["CieAnalyzedPixels"] = "{0:N0} pixels analyzed  ·  Below 0.01 nits excluded",
            ["MarkerMaximum"] = "MAX",
            ["MarkerMinimum"] = "MIN",
            ["CursorOn"] = "Cursor visible",
            ["CursorOff"] = "Cursor hidden",
            ["NeedOutput"] = "At least one output display is required.",
            ["SessionStarted"] = "The mirroring session has already started.",
            ["OpenAdapterFailed"] = "The GPU for the capture display could not be reopened.",
            ["OpenCaptureFailed"] = "The capture display could not be reopened.",
            ["D3DReady"] = "Direct3D 11 is ready and waiting for the first frame…",
            ["AnalysisD3DReady"] = "The Direct3D 11 analysis pipeline is ready and waiting for the first frame…",
            ["SecureDesktopWaiting"] = "Windows secure desktop detected. Mirroring is paused and will resume automatically after the administrator prompt closes.",
            ["AnalysisSecureDesktopWaiting"] = "Windows secure desktop detected. Analysis is paused and will resume automatically after the administrator prompt closes.",
            ["SecureDesktopPaused"] = "Paused for secure desktop",
            ["CaptureResumed"] = "Secure desktop closed. Resuming mirroring…",
            ["AnalysisCaptureResumed"] = "Secure desktop closed. Resuming analysis…",
            ["OutputCrossGpu"] = "Output display {0} is not on the capture GPU. Cross GPU output is not supported.",
            ["OpenOutputFailed"] = "Output display {0} could not be opened.",
            ["Fp16Unsupported"] = "Output display {0} does not support an FP16 scRGB swap chain. Confirm that Windows HDR is enabled.",
            ["FrameLatencyUnavailable"] = "A frame latency waitable object could not be created for output display {0}.",
            ["FrameLatencyWaitFailed"] = "Waiting for the output display to accept the next frame failed.",
            ["FrameRateWaitFailed"] = "Waiting for the next fixed frame rate deadline failed.",
            ["Hdr"] = "HDR",
            ["SdrFallback"] = "SDR fallback",
            ["CursorDisabled"] = "disabled",
            ["CursorHidden"] = "hidden",
            ["CursorRendered"] = "rendered",
            ["CursorWaiting"] = "waiting for shape",
            ["RunningStatus"] = "Running  {0:F1} fps  input={1}  {2}  size={3}×{4}  cursor={5}  frames={6}",
            ["Running"] = "Running",
            ["UnsupportedFormat"] = "Unsupported capture format: {0}.",
            ["InvalidPointerBuffer"] = "Desktop Duplication returned an invalid pointer shape buffer size.",
            ["AppStartFailed"] = "HDRScreenMirror failed to start",
            ["AblProfilesTitle"] = "ABL luminance profiles",
            ["AblProfiles"] = "Profiles",
            ["AblMeasurements"] = "Window peak luminance",
            ["AblProfileName"] = "Profile name",
            ["AblEotfTitle"] = "Peak luminance EOTF",
            ["AblEotfReset"] = "Restore standard PQ",
            ["AblEotfNoPeak"] = "Enter the 1% APL peak luminance first",
            ["AblEotfClipValue"] = "Clipping point  PQ {0:F1}%  ·  {1} nits",
            ["AblAplColumn"] = "APL",
            ["AblPeakColumn"] = "Peak luminance (nits)",
            ["AblRequiredApl"] = "{0}%  Required",
            ["AblNew"] = "New",
            ["AblDuplicate"] = "Duplicate",
            ["AblDelete"] = "Delete",
            ["AblSave"] = "Save",
            ["AblCancel"] = "Cancel",
            ["AblDefaultProfileName"] = "Profile {0}",
            ["AblCopyName"] = "{0} copy",
            ["AblDeleteConfirm"] = "Delete profile “{0}”?",
            ["AblDeleteTitle"] = "Delete ABL profile",
            ["AblInvalidPeak"] = "Luminance must be a number greater than 0 and no greater than 10000.",
            ["AblInvalidProfileTitle"] = "Incomplete ABL profile",
            ["AblInvalidProfile"] = "Profile “{0}” requires a name plus 1% and 100% peak luminance values.",
            ["AblUnnamedProfile"] = "Unnamed profile",
            ["AblEmptyTitle"] = "No ABL profile yet",
            ["AblEmptyHelp"] = "Select the blue “New” button on the left, then enter peak luminance at 1% and 100% APL."
        };

    private static UiLanguage _current = DetectWindowsLanguage();

    static Localization()
    {
        string[] missingEnglish = ChineseStrings.Keys.Except(EnglishStrings.Keys).ToArray();
        string[] missingChinese = EnglishStrings.Keys.Except(ChineseStrings.Keys).ToArray();
        if (missingEnglish.Length > 0 || missingChinese.Length > 0)
        {
            throw new InvalidOperationException(
                $"Localization keys do not match. Missing English: {string.Join(", ", missingEnglish)}; " +
                $"missing Chinese: {string.Join(", ", missingChinese)}.");
        }
    }

    public static UiLanguage Current => _current;

    public static void SetPreference(string? preference)
    {
        _current = preference switch
        {
            SimplifiedChinese => UiLanguage.Chinese,
            English => UiLanguage.English,
            _ => DetectWindowsLanguage()
        };
    }

    public static string T(string key)
    {
        IReadOnlyDictionary<string, string> strings =
            _current == UiLanguage.Chinese ? ChineseStrings : EnglishStrings;
        return strings.TryGetValue(key, out string? value) ? value : key;
    }

    public static string F(string key, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, T(key), arguments);

    private static UiLanguage DetectWindowsLanguage() =>
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("zh", StringComparison.OrdinalIgnoreCase)
            ? UiLanguage.Chinese
            : UiLanguage.English;
}
