from pathlib import Path


def read(path):
    return Path(path).read_text(encoding='utf-8')


def write(path, text):
    Path(path).write_text(text, encoding='utf-8', newline='\n')


def replace_once(path, old, new):
    text = read(path)
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f'{path}: expected one match, found {count}: {old[:80]!r}')
    write(path, text.replace(old, new, 1))


def replace_between(path, start, end, replacement):
    text = read(path)
    i = text.find(start)
    if i < 0:
        raise RuntimeError(f'{path}: start marker not found: {start!r}')
    j = text.find(end, i)
    if j < 0:
        raise RuntimeError(f'{path}: end marker not found: {end!r}')
    write(path, text[:i] + replacement + text[j:])


replace_once('src/HDRScreenMirror/HDRScreenMirror.csproj', '    <UseWindowsForms>true</UseWindowsForms>\n', '    <UseWindowsForms>true</UseWindowsForms>\n    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>\n')
replace_once('src/HDRScreenMirror/Program.cs', '        NativeMethods.TryEnablePerMonitorDpiAwareness();\n\n', '')
replace_once('src/HDRScreenMirror/Interop/NativeMethods.cs', '    private static readonly nint DpiAwarenessContextPerMonitorAwareV2 = new(-4);\n', '')
replace_once('src/HDRScreenMirror/Interop/NativeMethods.cs', '    [LibraryImport("user32.dll")]\n    [return: MarshalAs(UnmanagedType.Bool)]\n    private static partial bool SetProcessDpiAwarenessContext(nint value);\n\n', '')
replace_once('src/HDRScreenMirror/Interop/NativeMethods.cs', '    internal static void TryEnablePerMonitorDpiAwareness()\n    {\n        try\n        {\n            SetProcessDpiAwarenessContext(DpiAwarenessContextPerMonitorAwareV2);\n        }\n        catch (EntryPointNotFoundException)\n        {\n        }\n    }\n\n', '')

replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', 'using System.Drawing.Text;\nusing HDRScreenMirror.Interop;\n', 'using System.Drawing.Text;\nusing HDRScreenMirror.DirectX;\nusing HDRScreenMirror.Interop;\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '    private const int HighDpiLayoutBaseline = 144;\n', '')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '    private bool _falseColor;\n', '    private FalseColorMode _falseColorMode;\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '        _falseColor = falseColor;\n', '        _falseColorMode = falseColor ? FalseColorMode.Luminance : FalseColorMode.None;\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '    public void SetFalseColor(bool enabled)\n    {\n        if (_falseColor == enabled)\n            return;\n\n        _falseColor = enabled;\n        ResizeForContent();\n    }\n', '    public void SetFalseColor(bool enabled) =>\n        SetFalseColorMode(enabled ? FalseColorMode.Luminance : FalseColorMode.None);\n\n    public void SetFalseColorMode(FalseColorMode mode)\n    {\n        if (_falseColorMode == mode)\n            return;\n\n        _falseColorMode = mode;\n        ResizeForContent();\n    }\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '        if (_falseColor)\n            DrawFalseColorLegend(graphics, nextY);\n', '        if (_falseColorMode == FalseColorMode.Luminance)\n            DrawFalseColorLegend(graphics, nextY);\n        else if (_falseColorMode == FalseColorMode.Gamut)\n            DrawGamutFalseColorLegend(graphics, nextY);\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '    private void DrawFooter(Graphics graphics)\n', '    private void DrawGamutFalseColorLegend(Graphics graphics, int y)\n    {\n        using SolidBrush sectionBrush = new(SecondaryTextColor);\n        graphics.DrawString(\n            Localization.T("OverlayGamutFalseColor"),\n            _sectionFont,\n            sectionBrush,\n            OuterPadding,\n            y);\n\n        Color[] colors =\n        [\n            Color.FromArgb(71, 214, 255),\n            Color.FromArgb(255, 213, 79),\n            Color.FromArgb(229, 105, 255),\n            Color.FromArgb(255, 65, 51)\n        ];\n        string[] labels = ["sRGB", "P3+", "BT.2020+", Localization.T("CieOutside")];\n        int legendY = y + 23;\n        int legendWidth = PanelWidth - OuterPadding * 2;\n        int segmentWidth = legendWidth / colors.Length;\n        Rectangle legendBounds = new(OuterPadding, legendY, legendWidth, 13);\n        using GraphicsPath clipPath = CreateRoundedRectangle(legendBounds, 6);\n        GraphicsState state = graphics.Save();\n        graphics.SetClip(clipPath);\n        for (int i = 0; i < colors.Length; i++)\n        {\n            int width = i == colors.Length - 1 ? legendWidth - segmentWidth * i : segmentWidth + 1;\n            using SolidBrush brush = new(colors[i]);\n            graphics.FillRectangle(brush, OuterPadding + i * segmentWidth, legendY, width, 13);\n        }\n        graphics.Restore(state);\n\n        using SolidBrush labelBrush = new(MutedTextColor);\n        using StringFormat centered = new() { Alignment = StringAlignment.Center, LineAlignment = StringAlignment.Near };\n        for (int i = 0; i < labels.Length; i++)\n        {\n            Rectangle labelBounds = new(\n                OuterPadding + i * segmentWidth,\n                legendY + 16,\n                i == labels.Length - 1 ? legendWidth - i * segmentWidth : segmentWidth,\n                18);\n            graphics.DrawString(labels[i], _footerFont, labelBrush, labelBounds, centered);\n        }\n    }\n\n    private void DrawFooter(Graphics graphics)\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '        if (_falseColor)\n            height += 68;\n', '        if (_falseColorMode != FalseColorMode.None)\n            height += 68;\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '    private void ApplyDpi(int dpi)\n    {\n        float newScale = Math.Max(1f, dpi / (float)HighDpiLayoutBaseline);\n        _dpiScale = newScale;\n        RecreateFonts(dpi);\n', '    private void ApplyDpi(int dpi)\n    {\n        _dpiScale = Math.Max(0.5f, dpi / 96f);\n        RecreateFonts();\n')
replace_once('src/HDRScreenMirror/UI/StatusOverlayForm.cs', '    private void RecreateFonts(int dpi)\n    {\n        float pixelScale = dpi / 96f / _dpiScale;\n        ReplaceFont(ref _titleFont, 11.33f * pixelScale, FontStyle.Bold);\n        ReplaceFont(ref _stateFont, 11.33f * pixelScale, FontStyle.Bold);\n        ReplaceFont(ref _bodyFont, 12f * pixelScale, FontStyle.Regular);\n        ReplaceFont(ref _sectionFont, 11.33f * pixelScale, FontStyle.Bold);\n        ReplaceFont(ref _captionFont, 10.67f * pixelScale, FontStyle.Regular);\n        ReplaceFont(ref _valueFont, 16f * pixelScale, FontStyle.Bold);\n        ReplaceFont(ref _footerFont, 10.67f * pixelScale, FontStyle.Regular);\n    }\n', '    private void RecreateFonts()\n    {\n        ReplaceFont(ref _titleFont, 11.33f, FontStyle.Bold);\n        ReplaceFont(ref _stateFont, 11.33f, FontStyle.Bold);\n        ReplaceFont(ref _bodyFont, 12f, FontStyle.Regular);\n        ReplaceFont(ref _sectionFont, 11.33f, FontStyle.Bold);\n        ReplaceFont(ref _captionFont, 10.67f, FontStyle.Regular);\n        ReplaceFont(ref _valueFont, 16f, FontStyle.Bold);\n        ReplaceFont(ref _footerFont, 10.67f, FontStyle.Regular);\n    }\n')

replace_once('src/HDRScreenMirror/UI/AnalysisOverlayForm.cs', '    private readonly bool _excludeFromCapture;\n    private readonly ModeRotation _rotation;\n', '    private readonly bool _excludeFromCapture;\n    private readonly ModeRotation _rotation;\n    private readonly Rectangle _outputBounds;\n')
replace_once('src/HDRScreenMirror/UI/AnalysisOverlayForm.cs', '        _rotation = capture.Rotation;\n', '        _rotation = capture.Rotation;\n        _outputBounds = outputBounds;\n')
replace_once('src/HDRScreenMirror/UI/AnalysisOverlayForm.cs', '        StartPosition = FormStartPosition.Manual;\n        Bounds = outputBounds;\n', '        StartPosition = FormStartPosition.Manual;\n        AutoScaleMode = AutoScaleMode.None;\n        Bounds = outputBounds;\n')
replace_once('src/HDRScreenMirror/UI/AnalysisOverlayForm.cs', '    protected override void OnPaintBackground(PaintEventArgs eventArgs)\n', '    protected override void OnDpiChanged(DpiChangedEventArgs eventArgs)\n    {\n        base.OnDpiChanged(eventArgs);\n        Bounds = _outputBounds;\n        Invalidate();\n    }\n\n    protected override void OnPaintBackground(PaintEventArgs eventArgs)\n')

replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '    private readonly CheckBox _falseColor = CreateOptionCheckBox("FalseColor", false);\n', '    private readonly CheckBox _falseColor = CreateOptionCheckBox("FalseColor", false);\n    private readonly CheckBox _gamutFalseColor = CreateOptionCheckBox("GamutFalseColor", false);\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '    private bool _updatingDisplaySelection;\n', '    private bool _updatingDisplaySelection;\n    private bool _updatingFalseColorSelection;\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '        StartPosition = FormStartPosition.CenterScreen;\n        AutoScaleMode = AutoScaleMode.Dpi;\n', '        StartPosition = FormStartPosition.CenterScreen;\n        AutoScaleDimensions = new SizeF(96f, 96f);\n        AutoScaleMode = AutoScaleMode.Dpi;\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '        Controls.Add(BuildLayout());\n', '        Controls.Add(BuildScrollableLayout());\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '        _falseColor.CheckedChanged += (_, _) => UpdateFalseColorMode();\n', '        _falseColor.CheckedChanged += (_, _) => UpdateFalseColorMode(FalseColorMode.Luminance);\n        _gamutFalseColor.CheckedChanged += (_, _) => UpdateFalseColorMode(FalseColorMode.Gamut);\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '    private Control BuildLayout()\n    {\n', '    private Control BuildScrollableLayout()\n    {\n        Panel host = new()\n        {\n            Dock = DockStyle.Fill,\n            AutoScroll = true,\n            BackColor = Color.FromArgb(248, 249, 251)\n        };\n        Control layout = BuildLayout();\n        host.Controls.Add(layout);\n        return host;\n    }\n\n    private Control BuildLayout()\n    {\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '            Dock = DockStyle.Fill,\n            Padding = new Padding(20, 18, 20, 18),\n            ColumnCount = 2,\n            RowCount = 12,\n', '            Dock = DockStyle.Top,\n            AutoSize = true,\n            AutoSizeMode = AutoSizeMode.GrowAndShrink,\n            Padding = new Padding(20, 18, 20, 18),\n            ColumnCount = 2,\n            RowCount = 12,\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));\n', '        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 140));\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '    private Control BuildColorAnalysisOptions()\n    {\n        FlowLayoutPanel row = new() { Dock = DockStyle.Fill, FlowDirection = FlowDirection.LeftToRight };\n        row.Controls.Add(_showCieAnalysis);\n        return row;\n    }\n', '    private Control BuildColorAnalysisOptions()\n    {\n        FlowLayoutPanel row = new() { Dock = DockStyle.Fill, FlowDirection = FlowDirection.LeftToRight };\n        row.Controls.Add(_gamutFalseColor);\n        row.Controls.Add(_showCieAnalysis);\n        return row;\n    }\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '            AblProfile? activeAblProfile =\n                _showAblEstimate.Checked ? GetActiveAblProfile() : null;\n', '            AblProfile? activeAblProfile =\n                _showAblEstimate.Checked ? GetActiveAblProfile() : null;\n            FalseColorMode falseColorMode = analysisOnly ? FalseColorMode.None : GetFalseColorMode();\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '                    _showPointerLuminance.Checked,\n                    !analysisOnly && _falseColor.Checked,\n                    analysisOnly: analysisOnly);\n                overlay.SetAblEstimate(\n', '                    _showPointerLuminance.Checked,\n                    falseColorMode == FalseColorMode.Luminance,\n                    analysisOnly: analysisOnly);\n                overlay.SetFalseColorMode(falseColorMode);\n                overlay.SetAblEstimate(\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '                analysisOnly || _renderCursor.Checked,\n                !analysisOnly && _falseColor.Checked,\n                true);\n', '                analysisOnly || _renderCursor.Checked,\n                falseColorMode == FalseColorMode.Luminance,\n                true);\n            _session.SetFalseColorMode(falseColorMode);\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '        _falseColor.Enabled = !analysisMode;\n', '        _falseColor.Enabled = !analysisMode;\n        _gamutFalseColor.Enabled = !analysisMode;\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '    private void UpdateFalseColorMode()\n    {\n        bool enabled = !_singleDisplayAnalysis && _falseColor.Checked;\n        _session?.SetFalseColor(enabled);\n        foreach (StatusOverlayForm overlay in _statusOverlays)\n            overlay.SetFalseColor(enabled);\n    }\n', '    private FalseColorMode GetFalseColorMode() =>\n        _gamutFalseColor.Checked\n            ? FalseColorMode.Gamut\n            : _falseColor.Checked\n                ? FalseColorMode.Luminance\n                : FalseColorMode.None;\n\n    private void UpdateFalseColorMode(FalseColorMode changedMode)\n    {\n        if (_updatingFalseColorSelection)\n            return;\n\n        _updatingFalseColorSelection = true;\n        try\n        {\n            if (changedMode == FalseColorMode.Luminance && _falseColor.Checked)\n                _gamutFalseColor.Checked = false;\n            else if (changedMode == FalseColorMode.Gamut && _gamutFalseColor.Checked)\n                _falseColor.Checked = false;\n        }\n        finally\n        {\n            _updatingFalseColorSelection = false;\n        }\n\n        FalseColorMode mode = _singleDisplayAnalysis ? FalseColorMode.None : GetFalseColorMode();\n        _session?.SetFalseColorMode(mode);\n        foreach (StatusOverlayForm overlay in _statusOverlays)\n            overlay.SetFalseColorMode(mode);\n    }\n')
replace_once('src/HDRScreenMirror/UI/ControlForm.cs', '            bool falseColorEnabled = _falseColor.Checked;\n', '            bool falseColorEnabled = GetFalseColorMode() != FalseColorMode.None;\n')

replace_once('src/HDRScreenMirror/DirectX/MirrorSession.cs', '    private int _falseColorEnabled;\n', '    private int _falseColorMode;\n')
replace_once('src/HDRScreenMirror/DirectX/MirrorSession.cs', '        _falseColorEnabled = falseColor ? 1 : 0;\n', '        _falseColorMode = falseColor ? (int)FalseColorMode.Luminance : (int)FalseColorMode.None;\n')
replace_once('src/HDRScreenMirror/DirectX/MirrorSession.cs', '    public void SetFalseColor(bool enabled) =>\n        Volatile.Write(ref _falseColorEnabled, enabled ? 1 : 0);\n\n', '    public void SetFalseColor(bool enabled) =>\n        SetFalseColorMode(enabled ? FalseColorMode.Luminance : FalseColorMode.None);\n\n    public void SetFalseColorMode(FalseColorMode mode) =>\n        Volatile.Write(ref _falseColorMode, (int)mode);\n\n')
replace_once('src/HDRScreenMirror/DirectX/MirrorSession.cs', '        float x = imageViewport.X + (_cursorX - _cursorHotSpotX) * scale;\n        float y = imageViewport.Y + (_cursorY - _cursorHotSpotY) * scale;\n', '        float x = imageViewport.X + _cursorX * scale;\n        float y = imageViewport.Y + _cursorY * scale;\n')
replace_once('src/HDRScreenMirror/DirectX/MirrorSession.cs', '            FalseColorEnabled = Volatile.Read(ref _falseColorEnabled) != 0 ? 1u : 0u,\n', '            FalseColorMode = (uint)Volatile.Read(ref _falseColorMode),\n')
replace_once('src/HDRScreenMirror/DirectX/MirrorSession.cs', '        public uint FalseColorEnabled;\n', '        public uint FalseColorMode;\n')
replace_once('src/HDRScreenMirror/DirectX/MirrorSession.cs', '        public void Dispose()\n        {\n            RenderTarget.Dispose();\n            BackBuffer.Dispose();\n            SwapChain.Dispose();\n        }\n', '        public void Dispose()\n        {\n            RenderTarget.Dispose();\n            BackBuffer.Dispose();\n            SwapChain.Dispose();\n            if (FrameLatencyWaitableObject != nint.Zero)\n                NativeMethods.CloseHandle(FrameLatencyWaitableObject);\n        }\n')

replace_once('src/HDRScreenMirror/Shaders/Gamut.hlsl', '#include "LuminanceCommon.hlsli"\n', '#include "LuminanceCommon.hlsli"\n#include "GamutCommon.hlsli"\n')
replace_between('src/HDRScreenMirror/Shaders/Gamut.hlsl', 'float3 Rec709ToDciP3(float3 value)\n', 'float3 Rec709ToXYZ(float3 value)\n', '')
replace_once('src/HDRScreenMirror/Shaders/Gamut.hlsl', '    float3 linearRgb = DecodeLinearRgb(source);\n    float3 rec709 = InputMode == 2 ? Rec2020ToRec709(linearRgb) : linearRgb;\n    float3 dciP3 = InputMode == 2 ? Rec2020ToDciP3(linearRgb) : Rec709ToDciP3(linearRgb);\n    float3 rec2020 = InputMode == 2 ? linearRgb : Rec709ToRec2020(linearRgb);\n\n    uint category = IsInsideGamut(rec709) ? 0 :\n                    IsInsideGamut(dciP3) ? 1 :\n                    IsInsideGamut(rec2020) ? 2 : 3;\n', '    float3 linearRgb = DecodeLinearRgbForGamut(source, InputMode);\n    uint category = ClassifyGamut(linearRgb, InputMode);\n')

replace_once('src/HDRScreenMirror/Shaders/Mirror.hlsl', '    uint FalseColorEnabled;\n', '    uint FalseColorMode;\n')
replace_once('src/HDRScreenMirror/Shaders/Mirror.hlsl', '#include "LuminanceCommon.hlsli"\n', '#include "LuminanceCommon.hlsli"\n#include "GamutCommon.hlsli"\n')
replace_once('src/HDRScreenMirror/Shaders/Mirror.hlsl', '    if (FalseColorEnabled != 0)\n    {\n        float luminanceNits = CalculateLuminanceNits(rgbNits, InputMode);\n        float3 falseColorSrgb = MapNitsToFalseColor(luminanceNits);\n        return float4(SrgbToLinear(falseColorSrgb) * (PaperWhiteNits / 80.0), 1.0);\n    }\n', '    if (FalseColorMode == 1)\n    {\n        float luminanceNits = CalculateLuminanceNits(rgbNits, InputMode);\n        float3 falseColorSrgb = MapNitsToFalseColor(luminanceNits);\n        return float4(SrgbToLinear(falseColorSrgb) * (PaperWhiteNits / 80.0), 1.0);\n    }\n\n    if (FalseColorMode == 2)\n    {\n        float luminanceNits = CalculateLuminanceNits(rgbNits, InputMode);\n        if (luminanceNits < 0.01)\n            return float4(0.0, 0.0, 0.0, 1.0);\n        float3 linearRgb = DecodeLinearRgbForGamut(source, InputMode);\n        uint category = ClassifyGamut(linearRgb, InputMode);\n        float3 falseColorSrgb = MapGamutCategoryToFalseColor(category);\n        return float4(SrgbToLinear(falseColorSrgb) * (PaperWhiteNits / 80.0), 1.0);\n    }\n')
for path in ['src/HDRScreenMirror/Shaders/Gamut.hlsl', 'src/HDRScreenMirror/Shaders/Luminance.hlsl']:
    replace_once(path, '    uint FalseColorEnabled;\n', '    uint FalseColorMode;\n')

replace_once('src/HDRScreenMirror/Shaders/Luminance.hlsl', 'groupshared float SharedLuminanceTile[400];\ngroupshared uint SharedValidityTile[400];\n', 'groupshared float SharedLuminanceTile[400];\ngroupshared float SharedClippedLuminanceTile[400];\ngroupshared uint SharedValidityTile[400];\n')
replace_once('src/HDRScreenMirror/Shaders/Luminance.hlsl', '        SharedLuminanceTile[tileIndex] = tileLuminance;\n        SharedValidityTile[tileIndex] = tileValid ? 1 : 0;\n', '        SharedLuminanceTile[tileIndex] = tileLuminance;\n        SharedClippedLuminanceTile[tileIndex] = tileValid ? ApplyAblEotf(tileLuminance) : 0.0;\n        SharedValidityTile[tileIndex] = tileValid ? 1 : 0;\n')
replace_once('src/HDRScreenMirror/Shaders/Luminance.hlsl', '    float clippedLuminance = ApplyAblEotf(luminance);\n', '    float clippedLuminance = valid ? SharedClippedLuminanceTile[centerIndex] : 0.0;\n')
replace_once('src/HDRScreenMirror/Shaders/Luminance.hlsl', '                clippedRegionSum += ApplyAblEotf(SharedLuminanceTile[tileIndex]);\n', '                clippedRegionSum += SharedClippedLuminanceTile[tileIndex];\n')

replace_once('src/HDRScreenMirror/Localization.cs', '            ["FalseColor"] = "输出亮度伪色图",\n', '            ["FalseColor"] = "输出亮度伪色图",\n            ["GamutFalseColor"] = "输出色域伪色图",\n')
replace_once('src/HDRScreenMirror/Localization.cs', '            ["OverlayFalseColor"] = "亮度伪色色阶",\n', '            ["OverlayFalseColor"] = "亮度伪色色阶",\n            ["OverlayGamutFalseColor"] = "色域伪色分类",\n')
replace_once('src/HDRScreenMirror/Localization.cs', '            ["FalseColor"] = "Output luminance false color",\n', '            ["FalseColor"] = "Output luminance false color",\n            ["GamutFalseColor"] = "Output gamut false color",\n')
replace_once('src/HDRScreenMirror/Localization.cs', '            ["OverlayFalseColor"] = "FALSE COLOR SCALE",\n', '            ["OverlayFalseColor"] = "FALSE COLOR SCALE",\n            ["OverlayGamutFalseColor"] = "GAMUT FALSE COLOR",\n')

print('Core fixes applied.')
